title:               Chadwick Baseball Bureau
url:                 https://www.chadwick-bureau.com
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Dr Theodore L Turocy
  email:             ted.turocy@gmail.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist